-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 14:59:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurant` ;

-- -----------------------------------------------------
-- Table `restaurant`.`quaters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`quaters` (
  `id_quater` INT NOT NULL AUTO_INCREMENT,
  `quater_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_quater`),
  UNIQUE INDEX `id_quaters_UNIQUE` (`id_quater` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`countries` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `id_country_UNIQUE` (`id_country` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`cities` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `cityc_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_city`),
  UNIQUE INDEX `id_city_UNIQUE` (`id_city` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `quaters_id_quater` INT NOT NULL,
  `countries_id_country` INT NOT NULL,
  `cities_id_city` INT NOT NULL,
  PRIMARY KEY (`id_address`, `quaters_id_quater`, `countries_id_country`, `cities_id_city`),
  UNIQUE INDEX `id_address_UNIQUE` (`id_address` ASC) VISIBLE,
  INDEX `fk_address_quaters1_idx` (`quaters_id_quater` ASC) VISIBLE,
  INDEX `fk_address_countries1_idx` (`countries_id_country` ASC) VISIBLE,
  INDEX `fk_address_cities1_idx` (`cities_id_city` ASC) VISIBLE,
  CONSTRAINT `fk_address_quaters1`
    FOREIGN KEY (`quaters_id_quater`)
    REFERENCES `restaurant`.`quaters` (`id_quater`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_countries1`
    FOREIGN KEY (`countries_id_country`)
    REFERENCES `restaurant`.`countries` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_cities1`
    FOREIGN KEY (`cities_id_city`)
    REFERENCES `restaurant`.`cities` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`restaurant` (
  `restaurant_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `date_served` VARCHAR(45) NOT NULL,
  `date_of_preparation` VARCHAR(45) NOT NULL,
  `date_of_arrival` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`restaurant_id`),
  UNIQUE INDEX `id_restaurant_UNIQUE` (`restaurant_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`waiters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`waiters` (
  `id_waiters` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `address_id_address` INT NOT NULL,
  `address_quaters_id_quater` INT NOT NULL,
  `address_countries_id_country` INT NOT NULL,
  `address_cities_id_city` INT NOT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id_waiters`, `address_id_address`, `address_quaters_id_quater`, `address_countries_id_country`, `address_cities_id_city`, `restaurant_restaurant_id`),
  UNIQUE INDEX `id_waiters_UNIQUE` (`id_waiters` ASC) VISIBLE,
  INDEX `fk_waiters_address1_idx` (`address_id_address` ASC, `address_quaters_id_quater` ASC, `address_countries_id_country` ASC, `address_cities_id_city` ASC) VISIBLE,
  INDEX `fk_waiters_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_waiters_address1`
    FOREIGN KEY (`address_id_address` , `address_quaters_id_quater` , `address_countries_id_country` , `address_cities_id_city`)
    REFERENCES `restaurant`.`address` (`id_address` , `quaters_id_quater` , `countries_id_country` , `cities_id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_waiters_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `restaurant`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`dishes` (
  `id_dishes` INT NOT NULL AUTO_INCREMENT,
  `dishes_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `category_id_category` INT NOT NULL,
  `waiters_id_waiters` INT NOT NULL,
  `waiters_address_id_address` INT NOT NULL,
  `waiters_address_quaters_id_quater` INT NOT NULL,
  `waiters_address_countries_id_country` INT NOT NULL,
  `waiters_address_cities_id_city` INT NOT NULL,
  `waiters_restaurant_restaurant_id` INT NOT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id_dishes`, `category_id_category`, `waiters_id_waiters`, `waiters_address_id_address`, `waiters_address_quaters_id_quater`, `waiters_address_countries_id_country`, `waiters_address_cities_id_city`, `waiters_restaurant_restaurant_id`, `restaurant_restaurant_id`),
  UNIQUE INDEX `id_dishes_UNIQUE` (`id_dishes` ASC) VISIBLE,
  INDEX `fk_dishes_category1_idx` (`category_id_category` ASC) VISIBLE,
  INDEX `fk_dishes_waiters1_idx` (`waiters_id_waiters` ASC, `waiters_address_id_address` ASC, `waiters_address_quaters_id_quater` ASC, `waiters_address_countries_id_country` ASC, `waiters_address_cities_id_city` ASC, `waiters_restaurant_restaurant_id` ASC) VISIBLE,
  INDEX `fk_dishes_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_dishes_category1`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `restaurant`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_waiters1`
    FOREIGN KEY (`waiters_id_waiters` , `waiters_address_id_address` , `waiters_address_quaters_id_quater` , `waiters_address_countries_id_country` , `waiters_address_cities_id_city` , `waiters_restaurant_restaurant_id`)
    REFERENCES `restaurant`.`waiters` (`id_waiters` , `address_id_address` , `address_quaters_id_quater` , `address_countries_id_country` , `address_cities_id_city` , `restaurant_restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `restaurant`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`orders` (
  `id_orders` INT NOT NULL AUTO_INCREMENT,
  `customers_customer_id` INT NOT NULL,
  `dishes_id_dishes` INT NOT NULL,
  `dishes_category_id_category` INT NOT NULL,
  `dishes_waiters_id_waiters` INT NOT NULL,
  `dishes_waiters_address_id_address` INT NOT NULL,
  `dishes_waiters_address_quaters_id_quater` INT NOT NULL,
  `dishes_waiters_address_countries_id_country` INT NOT NULL,
  `dishes_waiters_address_cities_id_city` INT NOT NULL,
  `dishes_waiters_restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id_orders`, `customers_customer_id`, `dishes_id_dishes`, `dishes_category_id_category`, `dishes_waiters_id_waiters`, `dishes_waiters_address_id_address`, `dishes_waiters_address_quaters_id_quater`, `dishes_waiters_address_countries_id_country`, `dishes_waiters_address_cities_id_city`, `dishes_waiters_restaurant_restaurant_id`),
  UNIQUE INDEX `id_orders_UNIQUE` (`id_orders` ASC) VISIBLE,
  INDEX `fk_orders_customers_idx` (`customers_customer_id` ASC) VISIBLE,
  INDEX `fk_orders_dishes1_idx` (`dishes_id_dishes` ASC, `dishes_category_id_category` ASC, `dishes_waiters_id_waiters` ASC, `dishes_waiters_address_id_address` ASC, `dishes_waiters_address_quaters_id_quater` ASC, `dishes_waiters_address_countries_id_country` ASC, `dishes_waiters_address_cities_id_city` ASC, `dishes_waiters_restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customers_customer_id`)
    REFERENCES `restaurant`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_dishes1`
    FOREIGN KEY (`dishes_id_dishes` , `dishes_category_id_category` , `dishes_waiters_id_waiters` , `dishes_waiters_address_id_address` , `dishes_waiters_address_quaters_id_quater` , `dishes_waiters_address_countries_id_country` , `dishes_waiters_address_cities_id_city` , `dishes_waiters_restaurant_restaurant_id`)
    REFERENCES `restaurant`.`dishes` (`id_dishes` , `category_id_category` , `waiters_id_waiters` , `waiters_address_id_address` , `waiters_address_quaters_id_quater` , `waiters_address_countries_id_country` , `waiters_address_cities_id_city` , `waiters_restaurant_restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant`.`transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant`.`transfer` (
  `id_transfer` INT NOT NULL AUTO_INCREMENT,
  `date_of_transfer` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `restaurant_restaurant_id` INT NOT NULL,
  `dishes_id_dishes` INT NOT NULL,
  PRIMARY KEY (`id_transfer`),
  UNIQUE INDEX `id_transfer_UNIQUE` (`id_transfer` ASC) VISIBLE,
  INDEX `fk_transfer_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  INDEX `fk_transfer_dishes1_idx` (`dishes_id_dishes` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `restaurant`.`restaurant` (`restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_dishes1`
    FOREIGN KEY (`dishes_id_dishes`)
    REFERENCES `restaurant`.`dishes` (`id_dishes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
